name: verify
on: [ push ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: deno test